baseURL = 'https://e4exp.github.io/'
languageCode = 'ja-jp'
title = 'My New Hugo Site'
theme = 'github-style'


[params]
  author = "e4exp"
  description = ""
  github = ""
  url = ""
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "https://avatars.githubusercontent.com/u/44970465?s=400&u=ccaee68b8247f574ff10dfa82ed9702433a382c3&v=4"
  headerIcon = "/images/github-mark-white.png"

# 折りたたみ
[markup.goldmark.renderer]
  unsafe = true